# serverless.yml
service: anhnguyen-blog-service-apis

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: ap-southeast-1

functions:
  app:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    cors:
      - enabled: true
      - origin: 'http://admin.anhng.net'
    environment:
      NODE_ENV: production